---
cisco3:
  hostname: cisco3.lasthop.io
  username: pyclass
  password: password
  groups:
    - cisco
  data:
    key1: value1

cisco4:
  hostname: cisco4.lasthop.io
  username: pyclass
  password: password
  groups:
    - cisco

arista1:
  hostname: arista1.lasthop.io
  username: pyclass
  password: password
  groups:
    - arista

srx2:
  hostname: srx2.lasthop.io
  username: pyclass
  password: password
  groups:
    - juniper
